
package g5_6001066_6001063.interfacesG;

import javax.swing.JPanel;

public class CromosJF extends MetodosInterfaces{

    public CromosJF() {
        initComponents();
        
        setImageBtn(botonVolverCJB, "src/Icons/BotonVolver.png");
        botonVolverCJB.setPressedIcon(setImageBtn(botonVolverCJB, "src/Icons/BotonVolver.png"));
        setImageBtnRollover(botonVolverCJB, "src/Icons/BotonVolverMouse.gif");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoJP = new javax.swing.JPanel();
        botonVolverCJB = new javax.swing.JButton();
        fondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoJP.setMaximumSize(new java.awt.Dimension(1152, 648));
        fondoJP.setMinimumSize(new java.awt.Dimension(1152, 648));
        fondoJP.setPreferredSize(new java.awt.Dimension(1152, 648));
        fondoJP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonVolverCJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BotonVolver.png"))); // NOI18N
        botonVolverCJB.setBorder(null);
        botonVolverCJB.setMaximumSize(new java.awt.Dimension(179, 49));
        botonVolverCJB.setMinimumSize(new java.awt.Dimension(179, 49));
        botonVolverCJB.setPreferredSize(new java.awt.Dimension(179, 49));
        botonVolverCJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverCJBActionPerformed(evt);
            }
        });
        fondoJP.add(botonVolverCJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        fondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Fondo_Inicio.gif"))); // NOI18N
        fondoJP.add(fondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(fondoJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverCJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverCJBActionPerformed
        Pantalla pantalla = new Pantalla();
        cambiarPanel(fondoJP, pantalla.getInicioJP());
    }//GEN-LAST:event_botonVolverCJBActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolverCJB;
    private javax.swing.JLabel fondoInicio;
    private javax.swing.JPanel fondoJP;
    // End of variables declaration//GEN-END:variables

    public JPanel getFondoJP() {
        return fondoJP;
    }
    
}
