
package g5_6001066_6001063.interfacesG;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import javax.swing.JPanel;

public final class Pantalla extends MetodosInterfaces{
    
    private int mouseX, mouseY;
    
    public Pantalla() {
        initComponents();
        
        setImageBtn(botonCerrar, "src/Icons/BotonCerrar.png");
        botonCerrar.setPressedIcon(setImageBtn(botonCerrar, "src/Icons/BotonCerrar.png"));
        
        setImageBtn(botonMinimizar, "src/Icons/BotonMinimizar.png");
        botonMinimizar.setPressedIcon(setImageBtn(botonMinimizar, "src/Icons/BotonMinimizar.png"));
        
        InicioJF inicio = new InicioJF();
        cambiarPanel(inicioJP, inicio.getFondoJP());
        
        addDragFunctionality();
    }
    
        private void addDragFunctionality() {
        // Listener para detectar cuando se presiona el mouse en titleBarJP
        titleBarJP.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                // Guardar la posición del mouse cuando se presiona
                mouseX = evt.getX();
                mouseY = evt.getY();
            }
        });

        // Listener para mover la ventana mientras se arrastra el mouse en titleBarJP
        titleBarJP.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                // Obtener la posición actual del mouse y ajustar la posición de la ventana
                int x = evt.getXOnScreen() - mouseX;
                int y = evt.getYOnScreen() - mouseY;
                // Mover la ventana a la nueva ubicación
                setLocation(x, y);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBarJP = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JButton();
        botonMinimizar = new javax.swing.JButton();
        inicioJP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 225));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBarJP.setBackground(new java.awt.Color(251, 251, 237));
        titleBarJP.setMaximumSize(new java.awt.Dimension(1152, 30));
        titleBarJP.setMinimumSize(new java.awt.Dimension(1152, 30));
        titleBarJP.setPreferredSize(new java.awt.Dimension(1152, 30));
        titleBarJP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BotonCerrar.png"))); // NOI18N
        botonCerrar.setBorder(null);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        titleBarJP.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 20, 20));

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BotonMinimizar.png"))); // NOI18N
        botonMinimizar.setBorder(null);
        botonMinimizar.setMaximumSize(new java.awt.Dimension(20, 20));
        botonMinimizar.setMinimumSize(new java.awt.Dimension(20, 20));
        botonMinimizar.setPreferredSize(new java.awt.Dimension(20, 20));
        botonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMinimizarActionPerformed(evt);
            }
        });
        titleBarJP.add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 5, -1, -1));

        getContentPane().add(titleBarJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        inicioJP.setBackground(new java.awt.Color(0, 0, 0));
        inicioJP.setToolTipText("");
        inicioJP.setMaximumSize(new java.awt.Dimension(1152, 648));
        inicioJP.setMinimumSize(new java.awt.Dimension(1152, 648));
        inicioJP.setPreferredSize(new java.awt.Dimension(1152, 648));
        inicioJP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(inicioJP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMinimizarActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_botonMinimizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonMinimizar;
    private javax.swing.JPanel inicioJP;
    private javax.swing.JPanel titleBarJP;
    // End of variables declaration//GEN-END:variables

    public JPanel getInicioJP() {
        return inicioJP;
    }

    
}
